### ISSUE TITLE
kipfw segfaults on Centos7

### ISSUE THREAD

**Issue by awlx** [luigirizzo/netmap-ipfw#6]
Ixgbe version:
4.5.4
Kernelversion:
3.10.0-514.6.1.el7.x86_64
netmap version:
latest from Github

Output:

> ./kipfw netmap:ens1f0
> [ 521.214434] missing.c:main       [730] initializing tick to 200
> [ 521.214506] missing.c:callout_startup [365] start
> init_children mod_idx value 9
> +++ start module 0 ipfw ipfw at 0x62f240 order 0x1
> +++ start module 1 sy_ipfw SYSINIT at (nil) order 0x2
> ipfw2 initialized, divert loadable, nat loadable, default to accept, logging disabled
> +++ start module 2 sy_Vnet_ipfw SYSINIT at (nil) order 0x3
> [ 521.214769] missing.c:callout_init [312] c 0x6301e0 mpsafe 8
> [ 521.214814] missing.c:pfil_head_get [89] called
> [ 521.214829] missing.c:pfil_add_hook [96] called
> +++ start module 3 dummynet dummynet at 0x62f510 order 0x4
> DUMMYNET (nil) with IPv6 initialized (100409)
> [ 521.214882] missing.c:taskqueue_create_fast [431] start dummynet fn 0x420f00 ctx 0x6302c0
> [ 521.214895] missing.c:taskqueue_start_threads [439] tqp 0x6302c0 count 1 (dummy)
> [ 521.214908] missing.c:callout_init [312] c 0x6302e0 mpsafe 8
> +++ start module 4 dn_fifo dn_fifo at 0x62fad0 order 0x5
> [ 521.214939] ip_dummynet.c:load_dn_sched [2270] dn_sched FIFO loaded
> +++ start module 5 dn_wf2qp dn_wf2qp at 0x62fbb0 order 0x6
> [ 521.214972] ip_dummynet.c:load_dn_sched [2270] dn_sched WF2Q+ loaded
> +++ start module 6 dn_rr dn_rr at 0x62fc90 order 0x7
> [ 521.215012] ip_dummynet.c:load_dn_sched [2270] dn_sched RR loaded
> +++ start module 7 dn_qfq dn_qfq at 0x62fd70 order 0x8
> [ 521.215036] ip_dummynet.c:load_dn_sched [2270] dn_sched QFQ loaded
> +++ start module 8 dn_prio dn_prio at 0x62fe50 order 0x9
> [ 521.215054] ip_dummynet.c:load_dn_sched [2270] dn_sched PRIO loaded
> *** Global Sysctl Table entries = 45, total size = 2364 ***
> [ 521.215215] session.c:do_server  [557] +++ listening tcp 127.0.0.1:5555
> [ 521.215240] netmap_io.c:netmap_add_port [328] opening netmap device netmap:ens1f0
> [ 521.258849] netmap_io.c:netmap_add_port [344] --- mem_id 1
> [ 521.258873] netmap_io.c:netmap_add_port [347] create sess 0x1dfb750 my_netmap_port 0x1e041e0
> [ 521.259149] missing.c:callout_run [382] running 0x6302e0 due at 1 now 223
> [ 521.259169] session.c:mainloop   [640] callouts 1 skipped 0
> [ 522.000208] session.c:mainloop   [640] callouts 2767 skipped 0
> Segmentation fault

Any ideas what could go wrong? pkt-gen with netmap works without a problem.

**Comment by vmaffione** [comment]
No idea, but you may run it with gdb and print the backtrace to see where the problem is.
In any case, what is the meaning of specifying just one interface?

**Comment by awlx** [comment]
I resetup the machine and now it works.
